### ISSUE TITLE
Api that returns ledger gaps and last ledger sequence processed by importer

### ISSUE THREAD

**Issue by offlinehacker** [ripple/rippled-historical-database#109]
Currently there's no way to get ledger gaps and last ledger sequence from data api. We would need this for reliable transaction processing.

**Comment by shekenahglory** [comment]
if you run `/v2/ledgers` with no parameters, you'll get the last ledger imported - but its not guaranteed that all ledgers before that one have been imported.  It sounds like you are looking for the last ledger that was imported in unbroken sequence - right now we have 'v2/health/importer?verbose=true' which will show the time gap between now and the last imported (ledger gap) and last sequential (validation gap) - we could modify this endpoint to surface the sequence # of these as well.  Is that what you are looking for?

Also its important to note that some of the aggregated data can still contain gaps even if we've already imported all the ledgers, since the real time import process does not require those to be reliably calculated in order to advance.

**Comment by shekenahglory** [comment]
the health check now includes the last ledger imported in unbroken sequence as `last_validated_ledger` - https://data.ripple.com/v2/health/importer?verbose=true

**Comment by offlinehacker** [comment]
Thanks, this helps a lot!

**Comment by offlinehacker** [comment]
I'm closing this issue, as I think it's solved by having `last_validated_ledger` field.
