### ISSUE TITLE
xrp_distribution not updating & xrpcharts.ripple.com using incorrect data API endpoint for total XRP

### ISSUE THREAD

**Issue by professorhantzen** [ripple/rippled-historical-database#163]
Not sure if this is the right place to report an xrpcharts issue but this overlaps anyway.

https://xrpcharts.ripple.com/ is getting the "Total XRP" figure from https://data.ripple.com/v2/network/xrp_distribution

This endpoint appears to not be updating correctly - the latest figure is over three weeks old, and it further only has a weekly period when it is "up to date".  This figure also appears to be used to estimate the Market Capitalisation.

https://data.ripple.com/v2/ledgers "totalCoins" field on the other hand, has the Total XRP value updated every ledger.  Is there some reason this endpoint is not being used?

**Comment by shekenahglory** [comment]
The endpoint here is not updated automatically, it requires signoff from a few stake holders, and with the escrow changes and other concerns, the process is still being worked out a bit.  It is weekly by design, and the numbers indicate where totals stand at the end of the date specified.

XRP charts was using the ledger stream to dynamically update the total XRP number, I can switch it back to doing that for now.

**Comment by professorhantzen** [comment]
Right, that makes sense.  

Be great to at least make the total XRP number current, and this would bring the (total) market cap into regular alignment also.

Regarding any weekly-lagging indicators of the kind you've described, maybe should any relevant figures in xrpcharts/ripple.com be asterisked with a note approximating what you've written above?

**Comment by shekenahglory** [comment]
As far as I can recall, this was the only datapoint like that, the rest are either updated in realtime-ish or daily
