### ISSUE TITLE
This project is filled with major bugs that don't seem to get fixed.

### ISSUE THREAD

**Issue by professorhantzen** [ripple/rippled-historical-database#164]
Taking a scan down the Open Issues reveals major reproducible bugs that have existed for a long time and cause the API to return incorrect results.  Sometimes issues have replies, other times they seem to be ignored.  Some of the responses effectively say "this is a bug, do something else".

Is this project being actively maintained?  Should the README be changed to reflect this is not release software and to not expect it to work?

**Comment by inmyth** [comment]
As someone who has run historical data api I would say this software is very buggy and unstable.  I encountered many failures that resulted in "holes" / gaps, in the end the data was so fractured it's unusable. So the bottomline is: if you have a need for rippled historical data, you'd be better off building it yourself. 

How to do it ? That depends on which rippled. For public network then it's trivial because there's already public data api. I'd say people who need this the most are those who run private rippled network. In this case it is worth noting that transaction data from the first ledger can be retrieved from SQLite files stored in the rippled instance (default folder and files `/var/lib/rippled/db/*.db`). These files contain information that can be used to replicate the functionalities of data api. For example Transaction.db has information needed for data api's Get Account Transactions and Get Transactions.
